AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Daily tracker — buttons that write to Notion.

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        NOTION_TOKEN: !Ref NotionToken
        NOTION_DATABASE_ID: !Ref NotionDatabaseId

Parameters:
  NotionToken:
    Type: String
    NoEcho: true
    Description: Notion integration token
    Default: PLACEHOLDER
  NotionDatabaseId:
    Type: String
    Description: Notion database ID for the tracker
    Default: PLACEHOLDER

Resources:
  GetTodayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getToday/index.handler
      CodeUri: lambda/
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
          AllowHeaders:
            - Content-Type

  TrackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: track/index.handler
      CodeUri: lambda/
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - POST
          AllowHeaders:
            - Content-Type

Outputs:
  GetTodayUrl:
    Description: URL for the getToday function
    Value: !GetAtt GetTodayFunctionUrl.FunctionUrl
  TrackUrl:
    Description: URL for the track function
    Value: !GetAtt TrackFunctionUrl.FunctionUrl
